{{- if eq .Values.mode "daemon" }}
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroups: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  name: {{ .Values.clusterRole.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
{{- end }}
{{- end }}