{{- if eq .Values.mode "diag" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-diag-{{ .Values.parallelism }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-diag
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- if not .Values.nodeName }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              {{- if .Values.gpu}}
              - key: gpu_type 
                operator: Exists
              {{- else }}
              - key: gpu_type 
                operator: DoesNotExist
              {{- end }}
        {{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ .Values.name }}-diag
            topologyKey: "kubernetes.io/hostname"
      hostPID: true
      hostNetwork: true
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          {{- if .Values.gpu}}
          - name: NVIDIA_VISIBLE_DEVICES
            value: none
          {{- end }}
          command: ["/bin/bash"]
          args:
            - "-c"
            - |-
              output=$(sichek all -e)
              ret=$?
              if [[  $ret -ne 0 ]]; then
                 sichek all -e
              fi
              exit $ret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
  parallelism: {{ .Values.parallelism }}
{{- end }}
