Name: taskguard
Mode: pro
Log:
  Stat: true
KubeConfig:
  CheckStatusPeriod: 5m
  ResyncPeriod: 30m
  ConfigFile: /root/.kube/config
FaultToleranceConfig:
  EnableTaskGuardLabel: scitix.ai/taskguard
  CheckStatusPeriod: 1m
  MaxRetryCount: 3
  SiChekNodeAnnotationKey: scitix.ai/sichek
  LogCheckerRulesPath: /opt/taskguard/etc/log-checker-rules.yaml
  LogCheckerLines: 1000
