name: NVIDIA A800-SXM4-80GB
gpu_nums: 8
gpu_memory: 80
software:
  driver_version: 535.129.03
  cuda_version: 12.2
  vbios_version: 92.00.AC.00.03
  fabricmanager_version: 535.129.03
dependence:
  pcie_acs: disable
  iommu: off
  nv_peermem: enable
  nv_fabricmanager: active
  cpu_performance: enable
MaxClock:
  Graphics: 1410 # MHz
  Memory: 1593 # MHz
  SM: 1410 # MHz
nvlink:
  nvlink_supported: true
  active_nvlink_num: 8
  total_replay_errors: 0
  total_recovery_errors: 0
  total_crc_errors: 0
state:
  persistence: enable
  pstate: 0
memory_errors_threshold:
  remapped_uncorrectable_errors: 512
  sram_volatile_uncorrectable_errors: 0
  sram_aggregate_uncorrectable_errors: 4
  sram_volatile_correctable_errors: 10000000
  sram_aggregate_correctable_errors: 10000000
temperature_threshold:
  gpu: 75
  memory: 95