name: NVIDIA L40
gpu_nums: 8
gpu_memory: 80
software:
  driver_version: 535.129.03
  cuda_version: 12.2
  vbios_version: 95.02.39.00.01
  fabricmanager_version: 535.129.03
dependence:
  pcie_acs: disable
  iommu: off
  nv_peermem: enable
  nv_fabricmanager: Not Required
  cpu_performance: enable
MaxClock:
  Graphics: 2490 # MHz
  Memory: 9001 # MHz
  SM: 2490 # MHz
nvlink:
  nvlink_supported: false
  active_nvlink_num: 0
  total_replay_errors: 0
  total_recovery_errors: 0
  total_crc_errors: 0
state:
  persistence: enable
  pstate: 8 # For GPUs with an ADV architecture (graphics card type), when idle, the PCIe link speed will be reduced to save power, and the P-state will not be P0.
memory_errors_threshold:
  remapped_uncorrectable_errors: 512
  sram_volatile_uncorrectable_errors: 0
  sram_aggregate_uncorrectable_errors: 4
  sram_volatile_correctable_errors: 10000000
  sram_aggregate_correctable_errors: 10000000
temperature_threshold:
  gpu: 75
  memory: 95
