nvidia:
  "0x232c10de":
    name: NVIDIA H20 141GB HBM3e
    gpu_nums: 8
    gpu_memory: 141
    software:
      driver_version: ">=550.144.03"
      cuda_version: ">=12.4"
      vbios_version: "96.00.C3.00.02"
      fabricmanager_version: "550.144.03"
    dependence:
      pcie_acs: disable
      iommu: off
      nv_peermem: enable
      nv_fabricmanager: active
      cpu_performance: enable
    MaxClock:
      Graphics: 1980 # MHz
      SM: 1980 # MHz
      Memory: 3201 # MHz
    nvlink:
      nvlink_supported: true
      active_nvlink_num: 18
      total_replay_errors: 0
      total_recovery_errors: 0
      total_crc_errors: 0
    state:
      persistence: enable
      pstate: 0
    memory_errors_threshold:
      remapped_uncorrectable_errors: 512
      sram_volatile_uncorrectable_errors: 0
      sram_aggregate_uncorrectable_errors: 4
      sram_volatile_correctable_errors: 10000000
      sram_aggregate_correctable_errors: 10000000
    temperature_threshold:
      gpu: 75
      memory: 95
    perf: {}