nvidia:
  0x20b510de:
    name: NVIDIA A100 80GB PCIe
    gpu_nums: 8
    gpu_memory: 80
    software:
      driver_version: "470.199.02"
      cuda_version: "11.4"
      vbios_version: "92.00.A0.00.05"
      fabricmanager_version: "470.199.02"
    dependence:
      pcie_acs: disable
      iommu: off
      nv_peermem: enable
      nv_fabricmanager: Not Required
      cpu_performance: enable
    MaxClock:
      Graphics: 1410 # MHz
      SM: 1410 # MHz
      Memory: 1512 # MHz
    nvlink:
      nvlink_supported: false
      active_nvlink_num: 0
      total_replay_errors: 0
      total_recovery_errors: 0
      total_crc_errors: 0
    state:
      persistence: enable
      pstate: 0
    memory_errors_threshold:
      remapped_uncorrectable_errors: 512
      sram_volatile_uncorrectable_errors: 0
      sram_aggregate_uncorrectable_errors: 4
      sram_volatile_correctable_errors: 10000000
      sram_aggregate_correctable_errors: 10000000
    temperature_threshold:
      gpu: 75
      memory: 95
