nccl:
  name: NCCL
  log_dir: "/var/log/pods"
  query_interval: 30
  cache_size: 5
  checkers:
    TIMEOUT:
      name: "NCCL Timeout"
      description: "NCCL Timeout error"
      regexp: 'Watchdog caught collective operation timeout'
      level: error
