name: cpu
query_interval: 10
cache_size: 10
event_checkers:
  kernel_panic:
    name: "kernel_panic"
    description: "kernel panic are alerted"
    log_file: "/var/log/syslog"
    regexp: "kernel panic"
    level: critical
    suggestion: "restart node"
  cpu_overheating:
    name: "cpu_overheating"
    description: "CPU Core temperature is above threshold, cpu clock is throttled"
    log_file: "/var/log/syslog"
    regexp: "temperature above threshold"
    level: warning
    suggestion: ""
  cpu_lockup:
    name: "cpu_lockup"
    description: "CPU lockup occurs indicating the CPU cannot execute scheduled tasks due to software or hardware issues"
    log_file: "/var/log/syslog"
    regexp: "(soft lockup)|(hard LOCKUP)"
    level: warning
    suggestion: ""
info_checker: ["Intel(R) Xeon(R) Platinum 8468"]
