# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

project_name: taskguard

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: "taskguard"
    main: ./main.go
    binary: taskguard
    goos:
      - linux
    goarch:
      - amd64

# archives:
#   - format: tar.gz
#     # this name template makes the OS and Arch compatible with the results of `uname`.
#     name_template: >-
#       {{ .ProjectName }}_
#       {{- title .Os }}_
#       {{- if eq .Arch "amd64" }}x86_64
#       {{- else if eq .Arch "386" }}i386
#       {{- else }}{{ .Arch }}{{ end }}
#       {{- if .Arm }}v{{ .Arm }}{{ end }}
#     # use zip for windows archives
#     format_overrides:
#       - goos: windows
#         format: zip

nfpms:
  - id: "taskguard"
    formats:
      - deb
      - rpm
    package_name: taskguard
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    maintainer: hhu
    description: "taskguard"
    license: Apache 2.0
    contents:
    - src: ./bin/taskguard
      dst: /usr/sbin/taskguard
    - src: ./etc/config.yaml
      dst: /usr/sbin/etc/config.yaml
    - src: ./etc/log-checker-rules.yaml
      dst: /usr/sbin/etc/log-checker-rules.yaml
    # - src: ./.kube/config
    #   dst: /root/.kube/config

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
