nvidia:
  nvidia_spec:
    0x233010de:
      name: NVIDIA H100 80GB HBM3
      gpu_nums: 8
      gpu_memory: 80
      software:
        driver_version: ">=535.129.03"
        cuda_version: ">=12.2"
        vbios_version: "96.00.89.00.01"
        fabricmanager_version: ">=535.129.03"
      dependence:
        pcie_acs: disable
        iommu: off
        nv_peermem: enable
        nv_fabricmanager: active
        cpu_performance: enable
      nvlink:
        nvlink_supported: true
        active_nvlink_num: 18
        total_replay_errors: 0
        total_recovery_errors: 0
        total_crc_errors: 0
      state:
        persistence: enable
        pstate: 0
      memory_errors_threshold:
        remapped_uncorrectable_errors: 512
        sram_volatile_uncorrectable_errors: 0
        sram_aggregate_uncorrectable_errors: 4
        sram_volatile_correctable_errors: 10000000
        sram_aggregate_correctable_errors: 10000000
      temperature_threshold:
        gpu: 75
        memory: 95
infiniband:
  clusters:
    default:
      ib_devs:
        - mlx5_0
        - mlx5_1
        - mlx5_2
        - mlx5_3
      eth_devs:
        - ibs0
        - ibs1
        - ibs2
        - ibs3
      sw_deps:
        kernel_module:
          - "rdma_ucm"
          - "rdma_cm"
          - "ib_ipoib"
          - "mlx5_core"
          - "mlx5_ib"
          - "ib_uverbs"
          - "ib_umad"
          - "ib_cm"
          - "ib_core"
          - "mlxfw"
        ofed_ver: "MLNX_OFED_LINUX-23.10-1.1.9.0"
      pcie_acs: "disable"
      hca_specs:
        MT_0000000970:
          hca_type: "MT4129"
          board_id: "MT_0000000970"
          fw_ver: "28.39.2048"
          vpd: "P45645-001 / HPE InfiniBand NDR 1-port OSFP PCIe5 x16 MCX75310AAS-NEAT Adapter"
          net_port: 1
          port_speed: "400 Gb/sec (4X NDR)"
          phy_state: "LinkUp"
          port_state: "ACTIVE"
          net_operstate: "down"
          link_layer: "InfiniBand"
          pcie_width: "16"
          pcie_speed: "32.0 GT/s PCIe"
          pcie_tree_width: "32"
          pcie_tree_speed: "16"
          pcie_acs: "disable"
          pcie_mrr: "4096"