---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scitix-sa-taskguard
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scitix-cluster-role-taskguard
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - delete
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - events
      - nodes
    verbs:
      - get
      - list
      - watch
      - delete
      - patch
      - update
      - create
  - apiGroups:
      - kubeflow.org
    resources:
      - pytorchjobs
      - mpijobs
    verbs:
      - get
      - list
      - watch
      - delete
      - patch
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - get
      - list
      - watch
      - delete
      - patch
      - post
      - update
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scitix-cluster-role-binding-taskguard
  namespace: scitix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scitix-cluster-role-taskguard
subjects:
  - kind: ServiceAccount
    name: scitix-sa-taskguard
    namespace: scitix
