#!/bin/bash

# Post-install script for sichek package
# This script adds /var/sichek/scripts to the system PATH

set -e

SICHEK_SCRIPTS_PATH="/var/sichek/scripts"
PROFILE_D_FILE="/etc/profile.d/sichek.sh"

# Check if the scripts directory exists
if [ ! -d "$SICHEK_SCRIPTS_PATH" ]; then
    echo "Warning: $SICHEK_SCRIPTS_PATH does not exist"
    exit 0
fi

DEFAULT_SICHEK_SPEC_URL="https://oss-ap-southeast.scitix.ai/hisys-sichek/specs"
if [ -z "$SICHEK_SPEC_URL" ]; then
    SICHEK_SPEC_URL="$DEFAULT_SICHEK_SPEC_URL"
    echo "SICHEK_SPEC_URL not set, using default: $SICHEK_SPEC_URL"
else
    echo "Using existing SICHEK_SPEC_URL: $SICHEK_SPEC_URL"
fi

# Create the profile.d script
cat > "$PROFILE_D_FILE" << PROFILE_EOF
# sichek environment configuration
# This file is automatically generated by sichek package

# Add sichek scripts to PATH
export PATH="\$PATH:/var/sichek/scripts"
export SICHEK_SPEC_URL="$SICHEK_SPEC_URL"
PROFILE_EOF

# Make the file executable
chmod +x "$PROFILE_D_FILE"

# Set proper ownership
chown root:root "$PROFILE_D_FILE"

echo "Added /var/sichek/scripts to system PATH"
echo "SICHEK_SPEC_URL is set to ${SICHEK_SPEC_URL}"
source /etc/profile
echo "Please run 'source /etc/profile' or log out and log back in to use sichek scripts and SICHEK_SPEC_URL"

# Run check_sicl.sh
bash /var/sichek/scripts/check_sicl.sh || echo "Failed to run SICL installer"