#!/bin/bash

# Post-install script for sichek package
# This script adds /var/sichek/scripts to the system PATH

set -e

SICHEK_SCRIPTS_PATH="/var/sichek/scripts"
PROFILE_D_FILE="/etc/profile.d/sichek.sh"

# Check if the scripts directory exists
if [ ! -d "$SICHEK_SCRIPTS_PATH" ]; then
    echo "Warning: $SICHEK_SCRIPTS_PATH does not exist"
    exit 0
fi

# Create the profile.d script
cat > "$PROFILE_D_FILE" << 'PROFILE_EOF'
# Sichek scripts path
# This file is automatically generated by sichek package
export PATH="$PATH:/var/sichek/scripts"
PROFILE_EOF

# Make the file executable
chmod +x "$PROFILE_D_FILE"

# Set proper ownership
chown root:root "$PROFILE_D_FILE"

echo "Added /var/sichek/scripts to system PATH"
echo "Please run 'source /etc/profile' or log out and log back in to use sichek scripts"
