#!/bin/bash

# Post-install script for sichek package
# This script adds /var/sichek/scripts to the system PATH

set -e

SICHEK_SCRIPTS_PATH="/var/sichek/scripts"
PROFILE_D_FILE="/etc/profile.d/sichek.sh"

# Check if the scripts directory exists
if [ ! -d "$SICHEK_SCRIPTS_PATH" ]; then
    echo "Warning: $SICHEK_SCRIPTS_PATH does not exist"
    exit 0
fi

DEFAULT_SICHEK_SPEC_URL="https://oss-ap-southeast.scitix.ai/hisys-sichek/specs"
if [ -z "$SICHEK_SPEC_URL" ]; then
    SICHEK_SPEC_URL="$DEFAULT_SICHEK_SPEC_URL"
    echo "SICHEK_SPEC_URL not set, using default: $SICHEK_SPEC_URL"
else
    echo "Using existing SICHEK_SPEC_URL: $SICHEK_SPEC_URL"
fi

# Create the profile.d script
cat > "$PROFILE_D_FILE" << PROFILE_EOF
# sichek environment configuration
# This file is automatically generated by sichek package

# Add sichek scripts to PATH
export PATH="\$PATH:/var/sichek/scripts"
export SICHEK_SPEC_URL="$SICHEK_SPEC_URL"
PROFILE_EOF

# Make the file executable
chmod +x "$PROFILE_D_FILE"

# Set proper ownership
chown root:root "$PROFILE_D_FILE"

echo "Added /var/sichek/scripts to system PATH"
echo "SICHEK_SPEC_URL is set to ${SICHEK_SPEC_URL}"
source /etc/profile
echo "Please run 'source /etc/profile' or log out and log back in to use sichek scripts and SICHEK_SPEC_URL"

# Create AT wrapper scripts
# Usage: create_at_wrapper <wrapper_name> <python_script> [extra_args...]
create_at_wrapper() {
    local name="$1"
    local script="$2"
    shift 2
    local path="${SICHEK_SCRIPTS_PATH}/${name}"

    if [ ! -f "$script" ]; then
        echo "Warning: AT script not found: $script"
        return
    fi

    # Build escaped arguments string
    local escaped_args=""
    for arg in "$@"; do
        # Escape each argument properly for safe inclusion in the script
        escaped_args="${escaped_args} $(printf %q "$arg")"
    done

    # Create the wrapper script with properly escaped arguments
    cat > "$path" << WRAP_EOF
#!/usr/bin/env bash
exec python3 "$script"${escaped_args} "\$@"
WRAP_EOF

    chmod +x "$path"
    chown root:root "$path"
}

# Ensure atest scripts are executable
chmod +x "${SICHEK_SCRIPTS_PATH}/atest/"*.py 2>/dev/null || true

# Create sichek-config wrapper
CONFIG_WRAPPER_PATH="${SICHEK_SCRIPTS_PATH}/sichek-config"
if [ -f "${SICHEK_SCRIPTS_PATH}/atest/config.py" ]; then
    cat > "$CONFIG_WRAPPER_PATH" << 'CONFIG_EOF'
#!/usr/bin/env bash
exec python3 /var/sichek/scripts/atest/config.py "$@"
CONFIG_EOF
    chmod +x "$CONFIG_WRAPPER_PATH"
    chown root:root "$CONFIG_WRAPPER_PATH"
    echo "Created sichek-config wrapper"
else
    echo "Warning: config.py not found, skipping sichek-config wrapper"
fi

create_at_wrapper "sichek-k8s-nccltest-singlenode" "${SICHEK_SCRIPTS_PATH}/atest/nccltest_single_node.py" --request-gpu
create_at_wrapper "sichek-k8s-nccltest-multinode" "${SICHEK_SCRIPTS_PATH}/atest/nccltest_multi_node.py" --request-gpu
create_at_wrapper "sichek-k8s-nccltest-diag-singlenode" "${SICHEK_SCRIPTS_PATH}/atest/nccltest_single_node.py" --cmd "NCCL_DEBUG=INFO /usr/local/sihpc/libexec/nccl-tests/nccl_test -g 8 -b 8 -e 8"
create_at_wrapper "sichek-k8s-nccltest-diag-multinode" "${SICHEK_SCRIPTS_PATH}/atest/nccltest_multi_node.py" --cmd "allreduce -b 8 -e 8"
create_at_wrapper "sichek-k8s-llama2-13b" "${SICHEK_SCRIPTS_PATH}/atest/modeltest_single_node.py" --job-name sichek-llama2-13b
create_at_wrapper "sichek-k8s-llama2-70b" "${SICHEK_SCRIPTS_PATH}/atest/modeltest_multi_node.py" --job-name sichek-llama2-70b
create_at_wrapper "sichek-k8s-olmo3-7b" "${SICHEK_SCRIPTS_PATH}/atest/modeltest_single_node.py" --job-name sichek-olmo3-7b --cmd "bash /workspace/ai4s-job-system/mcore_trainer/demos/OLMo3/OLMo-3-1025-7B-pretrain-1.sh"
create_at_wrapper "sichek-k8s-olmo3-7b-multinode" "${SICHEK_SCRIPTS_PATH}/atest/modeltest_multi_node.py" --job-name sichek-olmo3-7b --cmd "bash /workspace/ai4s-job-system/mcore_trainer/demos/OLMo3/OLMo-3-1025-7B-pretrain-1.sh"
create_at_wrapper "sichek-k8s-qwen-a3b" "${SICHEK_SCRIPTS_PATH}/atest/modeltest_multi_node.py" --job-name sichek-qwen-a3b --cmd "MAX_STEPS=128 NCCL_DEBUG=WARN bash /workspace/ai4s-job-system/mcore_trainer/demos/deepseek/sft_deepseekv3.1_base.sh"

# Run check_sicl.sh
bash /var/sichek/scripts/check_sicl.sh || echo "Failed to run SICL installer"
