hca_specs:
  MT_0000000970:
    hca_type: "MT4129"
    board_id: "MT_0000000970"
    fw_ver: "28.39.2048"
    vpd: "P45645-001 / HPE InfiniBand NDR 1-port OSFP PCIe5 x16 MCX75310AAS-NEAT Adapter"
    net_port: 1
    port_speed: "400 Gb/sec (4X NDR)"
    phy_state: "LinkUp"
    port_state: "ACTIVE"
    net_operstate: "down"
    link_layer: "InfiniBand"
    pcie_width: "16"
    pcie_speed: "32.0 GT/s PCIe"
    pcie_tree_width: "32"
    pcie_tree_speed: "16"
    pcie_acs: "disable"
    pcie_mrr: "4096"