dmesg: 
  file_name: ["/var/log/dmesg"]
  # cmd:
  #   - ["dmesg"]
  event_checkers:
    SysOOM:
      name: "sys_oom"
      description: "oom error in dmesg"
      regexp: 'Out of memory:'
      level: error
    CgroupOOM:
      name: "cgroup_oom"
      description: "oom error in dmesg"
      regexp: 'Memory cgroup out of memory'
      level: error
    NVSXID:
      name: "nvidia_sxid"
      description: "nv sxid error in dmesg"
      regexp: 'SXid.*?: (\d+),'
      level: error
    NCCL:
      name: "nccl"
      description: "libnccl segment fault error in dmesg"
      regexp: '.*segfault at.*in libnccl\.so.*'
      level: error