dmesg:
  name: DMesg
  FileNmae: ["/var/log/dmesg"]
  Cmd:
    - ["dmesg"]
  query_interval: 30
  cache_size: 5
  checkers:
    OOM1:
      name: "oom"
      description: "oom error in dmesg"
      regexp: '(?i)\b(invoked|triggered) oom-killer\b'
      level: error
    OOM2:
      name: "oom"
      description: "oom error in dmesg"
      regexp: 'oom-kill:constraint='
      level: error
    OOM3:
      name: "oom"
      description: "oom error in dmesg"
      regexp: 'Out of memory:'
      level: error
    OOM4:
      name: "oom"
      description: "oom error in dmesg"
      regexp: 'Memory cgroup out of memory'
      level: error
    NVXID:
      name: "nvidia"
      description: "nv xid error in dmesg"
      regexp: 'NVRM: Xid.*?: (\d+),'
      level: error
    NVSXID:
      name: "nvidia"
      description: "nv sxid error in dmesg"
      regexp: 'SXid.*?: (\d+),'
      level: error
    PEERMEM:
      name: "peermem"
      description: "peermem invalid context error in dmesg"
      regexp: '.*ERROR detected invalid context, skipping further processing'
      level: error
    NCCL:
      name: "nccl"
      description: "libnccl segment fault error in dmesg"
      regexp: '.*segfault at.*in libnccl\.so.*'
      level: error
