hang:
  name: Hang
  query_interval: 10
  cache_size: 10
  nvsmi: false
  mock: true
  checkers:
    GPU:
      name: "GPUHang"
      description: "GPU Hang"
      hang_threshold: 600
      level: warn
      check_items:
        power:
          name: "pwr"
          threshold: 150
          compare: low
        # graph clk in nvml is zero when hang?
        gclk:
          name: "gclk"
          threshold: 1500
          compare: high
        # sm clk in nvml is zero when hang?
        smclk:
          name: "smclk"
          threshold: 1500
          compare: high
        # sm util in nvml is zero when hang?
        comp_util:
          name: "sm"
          threshold: 95
          compare: high
        mem_util:
          name: "mem"
          threshold: 5
          compare: low
        pviol:
          name: "pviol"
          threshold: 5
          compare: low
        rxpci:
          name: "rxpci"
          # MB/s
          threshold: 10
          compare: low
        txpci:
          name: "txpci"
          # MB/s
          threshold: 10
          compare: low
    # Network:
    #   name: "NetHang"
    #   description: "Network Hang"
    #   check_items:
    #     tx:
    #       name: "tx_bytes"
    #       threshold: 4096
    #       compare: low
    #     rx:
    #       name: "rx_bytes"
    #       threshold: 4096
    #       compare: low
    #   hang_threshold: 600
    #   level: warn
