hang:
  name: "GPUHang"
  description: "GPU Hang"
  duration_threshold: 2m30s
  level: warn
  check_items:
    power:
      threshold: 100
      compare: low
    gclk:
      threshold: 1400
      compare: high
    smclk:
      threshold: 1400
      compare: high
    sm_util:
      threshold: 95
      compare: high
    mem_util:
      threshold: 5
      compare: low
    pviol:
      threshold: 5
      compare: low
    rxpci:
      threshold: 20 # MB/s
      compare: low
    txpci:
      threshold: 20 # MB/s
      compare: low
  check_items_by_model:
    - model: "0x233010de"
      override:
        power:
          threshold: 150
          compare: low
        gclk:
          threshold: 1900
          compare: high
        smclk:
          threshold: 1900
          compare: high
