global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sichek-monitor'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first.rules"
  # - "second.rules"
  
scrape_configs:
  - job_name: 'prometheus_server'
    static_configs:
      - targets: ['156.59.222.170:9090']
  - job_name: 'exporter_server'
    static_configs:
      - targets: ['156.59.222.170:9091']

      
